#pragma once
// Every option in the menu lives in this one list (generated by gen_hacks.py).
// Add a line and it shows up in the menu automatically, saved and searchable.
#include <string>
#include <string_view>
#include <vector>

namespace ov {

enum class Type { Toggle, Float, Int, Choice };

// X(id, name, description, category, type, default, min, max, isCheat, choices)
#define OV_HACKS(X) \
    X(noclip, "Noclip", "You can't die.", "Player", Toggle, 0, 0, 1, true, "") \
    X(noclip_p1, "Noclip only player 1", "With Noclip on, player 2 can still die (dual).", "Player", Toggle, 0, 0, 1, false, "") \
    X(noclip_flash, "Noclip death flash", "Flash the screen red whenever you would have died.", "Player", Toggle, 1, 0, 1, false, "") \
    X(jump_hack, "Jump hack", "Jump in mid-air as cube, robot, ball and spider.", "Player", Toggle, 0, 0, 1, true, "") \
    X(autoclicker, "Auto clicker", "Clicks for you while it's on (Alt+A).", "Player", Toggle, 0, 0, 1, true, "") \
    X(autoclick_cps, "Auto clicker speed (CPS)", "Clicks per second.", "Player", Float, 10, 1, 120, false, "") \
    X(autoclick_hold, "Auto clicker hold (ticks)", "How long each click is held (240 ticks = 1 second).", "Player", Int, 2, 1, 120, false, "") \
    X(autoclick_p2, "Auto clicker player 2", "Also click for player 2 (two-player levels).", "Player", Toggle, 0, 0, 1, false, "") \
    X(frame_stepper, "Frame stepper", "Freezes the game. Press the Step key (F) to move one tick.", "Player", Toggle, 0, 0, 1, true, "") \
    X(custom_respawn, "Custom respawn time", "Respawn faster (or slower) after dying.", "Player", Toggle, 0, 0, 1, false, "") \
    X(respawn_delay, "Respawn time (seconds)", "Normal is about 1.0.", "Player", Float, 0.3, 0, 3, false, "") \
    X(no_death_effect, "No death effect", "No explosion when you die.", "Player", Toggle, 0, 0, 1, false, "") \
    X(hide_player, "Hide player", "Makes your icon invisible.", "Player", Toggle, 0, 0, 1, false, "") \
    X(hide_player2, "Hide player 2", "Makes only player 2 invisible (dual).", "Player", Toggle, 0, 0, 1, false, "") \
    X(no_spider_line, "No spider teleport line", "Removes the flash line when the spider teleports.", "Player", Toggle, 0, 0, 1, false, "") \
    X(safe_mode, "Safe mode", "While a cheat is on, the attempt never saves progress or completions. Keep this on!", "Player", Toggle, 1, 0, 1, false, "") \
    X(auto_practice, "Auto practice mode", "Starts every level in practice mode.", "Practice", Toggle, 0, 0, 1, false, "") \
    X(practice_music, "Practice music sync", "Practice mode plays the real song in sync.", "Practice", Toggle, 0, 0, 1, false, "") \
    X(auto_restart, "Auto restart at %", "Restarts the attempt when you reach the % below. Great for drilling a part.", "Practice", Toggle, 0, 0, 1, false, "") \
    X(restart_percent, "Restart at (%)", "Used by Auto restart.", "Practice", Float, 50, 1, 100, false, "") \
    X(death_markers, "Death markers", "A red X where you last died.", "Practice", Toggle, 0, 0, 1, false, "") \
    X(death_markers_all, "Keep every death marker", "Keep all X's instead of only the last one.", "Practice", Toggle, 0, 0, 1, false, "") \
    X(death_markers_noclip, "Markers for noclip deaths", "Also mark where you would have died with noclip.", "Practice", Toggle, 0, 0, 1, false, "") \
    X(pause_on_death, "Pause when you die", "Opens the pause menu every time you die.", "Practice", Toggle, 0, 0, 1, false, "") \
    X(noclip_practice_only, "Noclip only in practice", "Noclip does nothing outside practice mode.", "Practice", Toggle, 0, 0, 1, false, "") \
    X(speed_practice_only, "Speedhack only in practice", "Speedhack does nothing outside practice mode.", "Practice", Toggle, 0, 0, 1, false, "") \
    X(startpos_switcher, "StartPos switcher", "Cycle start positions with Q / E (change keys in mod settings).", "Level", Toggle, 1, 0, 1, false, "") \
    X(startpos_buttons, "StartPos buttons", "Arrows at the bottom of the screen to switch start positions (phones / tablets).", "Level", Toggle, 1, 0, 1, false, "") \
    X(accurate_percent, "Accurate percentage", "Percentage with decimals.", "Level", Toggle, 0, 0, 1, false, "") \
    X(percent_decimals, "Percentage decimals", "How many decimals.", "Level", Int, 2, 0, 5, false, "") \
    X(hitboxes, "Show hitboxes", "Draws every hitbox while you play (counts as a cheat, like in practice).", "Level", Toggle, 0, 0, 1, true, "") \
    X(hitboxes_on_death, "Hitboxes on death", "Shows hitboxes only after you die.", "Level", Toggle, 0, 0, 1, false, "") \
    X(no_mirror, "No mirror portals", "Mirror portals don't flip the screen (counts as a cheat).", "Level", Toggle, 0, 0, 1, true, "") \
    X(no_shake, "No camera shake", "Turns off screen shake.", "Level", Toggle, 0, 0, 1, false, "") \
    X(hide_attempts, "Hide attempt counter", "Hides the 'Attempt N' text.", "Level", Toggle, 0, 0, 1, false, "") \
    X(hide_pause, "Hide pause button", "Hides the pause button (Esc still works).", "Level", Toggle, 0, 0, 1, false, "") \
    X(hide_practice_btns, "Hide practice buttons", "Hides the checkpoint buttons.", "Level", Toggle, 0, 0, 1, false, "") \
    X(hide_progress, "Hide progress bar", "Hides the progress bar at the top.", "Level", Toggle, 0, 0, 1, false, "") \
    X(hide_percent, "Hide percentage", "Hides the % text.", "Level", Toggle, 0, 0, 1, false, "") \
    X(no_new_best, "Hide new best popup", "No 'New Best' popup when you die.", "Level", Toggle, 0, 0, 1, false, "") \
    X(speedhack, "Speedhack", "Speeds the whole game up or down (Alt+S).", "Speed", Toggle, 0, 0, 1, true, "") \
    X(speed, "Speed", "1 = normal, 0.5 = half speed, 2 = double. Alt+Up / Alt+Down change it.", "Speed", Float, 1, 0.05, 10, false, "") \
    X(speed_audio, "Speedhack changes music", "Music speeds up / slows down with the game.", "Speed", Toggle, 1, 0, 1, false, "") \
    X(speed_levels_only, "Speedhack only in levels", "Menus stay at normal speed.", "Speed", Toggle, 0, 0, 1, false, "") \
    X(speed_step, "Speed key step", "How much Alt+Up / Alt+Down change the speed.", "Speed", Float, 0.25, 0.05, 2, false, "") \
    X(slowmo_speed, "Slow-mo key speed", "Hold C in a level to play at this speed (counts as a cheat while held).", "Speed", Float, 0.5, 0.05, 1, false, "") \
    X(icon_cube_on, "Custom Cube icon", "Use the cube below instead of your own.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_cube, "Cube icon number", "Any cube, even locked ones (1-485).", "Icons", Int, 1, 1, 485, false, "") \
    X(icon_ship_on, "Custom Ship icon", "Use the ship below instead of your own.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_ship, "Ship icon number", "Any ship, even locked ones (1-169).", "Icons", Int, 1, 1, 169, false, "") \
    X(icon_ball_on, "Custom Ball icon", "Use the ball below instead of your own.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_ball, "Ball icon number", "Any ball, even locked ones (1-118).", "Icons", Int, 1, 1, 118, false, "") \
    X(icon_ufo_on, "Custom UFO icon", "Use the ufo below instead of your own.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_ufo, "UFO icon number", "Any ufo, even locked ones (1-149).", "Icons", Int, 1, 1, 149, false, "") \
    X(icon_wave_on, "Custom Wave icon", "Use the wave below instead of your own.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_wave, "Wave icon number", "Any wave, even locked ones (1-96).", "Icons", Int, 1, 1, 96, false, "") \
    X(icon_robot_on, "Custom Robot icon", "Use the robot below instead of your own (re-open the level to see a change).", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_robot, "Robot icon number", "Any robot, even locked ones (1-68).", "Icons", Int, 1, 1, 68, false, "") \
    X(icon_spider_on, "Custom Spider icon", "Use the spider below instead of your own (re-open the level to see a change).", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_spider, "Spider icon number", "Any spider, even locked ones (1-69).", "Icons", Int, 1, 1, 69, false, "") \
    X(icon_swing_on, "Custom Swing icon", "Use the swing below instead of your own.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_swing, "Swing icon number", "Any swing, even locked ones (1-43).", "Icons", Int, 1, 1, 43, false, "") \
    X(icon_jetpack_on, "Custom Jetpack icon", "Use the jetpack below instead of your own.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_jetpack, "Jetpack icon number", "Any jetpack, even locked ones (1-8).", "Icons", Int, 1, 1, 8, false, "") \
    X(icons_p2, "Player 2 uses custom icons", "Off = player 2 keeps your normal icons.", "Icons", Toggle, 1, 0, 1, false, "") \
    X(icon_random, "Random icons every attempt", "A new random icon for every gamemode each attempt.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_scale, "Icon size (looks only)", "Hitbox stays the same. 1 = normal.", "Icons", Float, 1, 0.25, 3, false, "") \
    X(icon_opacity, "Icon opacity", "1 = solid, 0.1 = almost invisible.", "Icons", Float, 1, 0.1, 1, false, "") \
    X(icon_spin, "Spinning icon", "Your icon spins nonstop (looks only).", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_spin_speed, "Spin speed", "Turns per second.", "Icons", Float, 1, 0.1, 10, false, "") \
    X(icon_mirror, "Mirror icon", "Flips your icon left-right.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_upside, "Upside-down icon", "Flips your icon top-bottom (looks only).", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_jelly, "Jelly icon", "Your icon squishes and stretches.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_shake, "Shaky icon", "Your icon jitters.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_flicker, "Flickering icon", "Your icon flickers like a ghost.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_glow_force, "Always glow", "Glow outline on, even if it's off in your garage.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(icon_glow_hide, "No glow", "Glow outline off.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(hide_vehicle_cube, "Hide cube in ship / UFO", "Removes the little cube riding the ship, UFO and jetpack.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(death_effect_on, "Custom death effect", "Use the death effect below.", "Icons", Toggle, 0, 0, 1, false, "") \
    X(death_effect, "Death effect number", "1 = default explosion, up to 20.", "Icons", Int, 1, 1, 20, false, "") \
    X(c_p1_main_mode, "P1 main colour", "Normal, a GD colour, your own RGB, rainbow or pulse.", "Colors", Choice, 0, 0, 4, false, "Normal|GD colour|Custom RGB|Rainbow|Pulse") \
    X(c_p1_main_idx, "P1 main colour: GD colour #", "Used when set to 'GD colour' (0-106, like the garage).", "Colors", Int, 12, 0, 106, false, "") \
    X(c_p1_main_r, "P1 main colour: red", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p1_main_g, "P1 main colour: green", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 80, 0, 255, false, "") \
    X(c_p1_main_b, "P1 main colour: blue", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 200, 0, 255, false, "") \
    X(c_p1_second_mode, "P1 second colour", "Normal, a GD colour, your own RGB, rainbow or pulse.", "Colors", Choice, 0, 0, 4, false, "Normal|GD colour|Custom RGB|Rainbow|Pulse") \
    X(c_p1_second_idx, "P1 second colour: GD colour #", "Used when set to 'GD colour' (0-106, like the garage).", "Colors", Int, 12, 0, 106, false, "") \
    X(c_p1_second_r, "P1 second colour: red", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 80, 0, 255, false, "") \
    X(c_p1_second_g, "P1 second colour: green", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 220, 0, 255, false, "") \
    X(c_p1_second_b, "P1 second colour: blue", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p1_glow_mode, "P1 glow colour", "Normal, a GD colour, your own RGB, rainbow or pulse. Glow only shows with glow on (Icons > Always glow).", "Colors", Choice, 0, 0, 4, false, "Normal|GD colour|Custom RGB|Rainbow|Pulse") \
    X(c_p1_glow_idx, "P1 glow colour: GD colour #", "Used when set to 'GD colour' (0-106, like the garage).", "Colors", Int, 12, 0, 106, false, "") \
    X(c_p1_glow_r, "P1 glow colour: red", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p1_glow_g, "P1 glow colour: green", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p1_glow_b, "P1 glow colour: blue", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p1_trail_mode, "P1 trail colour", "Normal, a GD colour, your own RGB, rainbow or pulse.", "Colors", Choice, 0, 0, 4, false, "Normal|GD colour|Custom RGB|Rainbow|Pulse") \
    X(c_p1_trail_idx, "P1 trail colour: GD colour #", "Used when set to 'GD colour' (0-106, like the garage).", "Colors", Int, 12, 0, 106, false, "") \
    X(c_p1_trail_r, "P1 trail colour: red", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p1_trail_g, "P1 trail colour: green", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p1_trail_b, "P1 trail colour: blue", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p1_wave_mode, "P1 wave trail colour", "Normal, a GD colour, your own RGB, rainbow or pulse.", "Colors", Choice, 0, 0, 4, false, "Normal|GD colour|Custom RGB|Rainbow|Pulse") \
    X(c_p1_wave_idx, "P1 wave trail colour: GD colour #", "Used when set to 'GD colour' (0-106, like the garage).", "Colors", Int, 12, 0, 106, false, "") \
    X(c_p1_wave_r, "P1 wave trail colour: red", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p1_wave_g, "P1 wave trail colour: green", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p1_wave_b, "P1 wave trail colour: blue", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_main_mode, "P2 main colour", "Normal, a GD colour, your own RGB, rainbow or pulse.", "Colors", Choice, 0, 0, 4, false, "Normal|GD colour|Custom RGB|Rainbow|Pulse") \
    X(c_p2_main_idx, "P2 main colour: GD colour #", "Used when set to 'GD colour' (0-106, like the garage).", "Colors", Int, 12, 0, 106, false, "") \
    X(c_p2_main_r, "P2 main colour: red", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_main_g, "P2 main colour: green", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 80, 0, 255, false, "") \
    X(c_p2_main_b, "P2 main colour: blue", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 200, 0, 255, false, "") \
    X(c_p2_second_mode, "P2 second colour", "Normal, a GD colour, your own RGB, rainbow or pulse.", "Colors", Choice, 0, 0, 4, false, "Normal|GD colour|Custom RGB|Rainbow|Pulse") \
    X(c_p2_second_idx, "P2 second colour: GD colour #", "Used when set to 'GD colour' (0-106, like the garage).", "Colors", Int, 12, 0, 106, false, "") \
    X(c_p2_second_r, "P2 second colour: red", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 80, 0, 255, false, "") \
    X(c_p2_second_g, "P2 second colour: green", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 220, 0, 255, false, "") \
    X(c_p2_second_b, "P2 second colour: blue", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_glow_mode, "P2 glow colour", "Normal, a GD colour, your own RGB, rainbow or pulse. Glow only shows with glow on (Icons > Always glow).", "Colors", Choice, 0, 0, 4, false, "Normal|GD colour|Custom RGB|Rainbow|Pulse") \
    X(c_p2_glow_idx, "P2 glow colour: GD colour #", "Used when set to 'GD colour' (0-106, like the garage).", "Colors", Int, 12, 0, 106, false, "") \
    X(c_p2_glow_r, "P2 glow colour: red", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_glow_g, "P2 glow colour: green", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_glow_b, "P2 glow colour: blue", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_trail_mode, "P2 trail colour", "Normal, a GD colour, your own RGB, rainbow or pulse.", "Colors", Choice, 0, 0, 4, false, "Normal|GD colour|Custom RGB|Rainbow|Pulse") \
    X(c_p2_trail_idx, "P2 trail colour: GD colour #", "Used when set to 'GD colour' (0-106, like the garage).", "Colors", Int, 12, 0, 106, false, "") \
    X(c_p2_trail_r, "P2 trail colour: red", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_trail_g, "P2 trail colour: green", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_trail_b, "P2 trail colour: blue", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_wave_mode, "P2 wave trail colour", "Normal, a GD colour, your own RGB, rainbow or pulse.", "Colors", Choice, 0, 0, 4, false, "Normal|GD colour|Custom RGB|Rainbow|Pulse") \
    X(c_p2_wave_idx, "P2 wave trail colour: GD colour #", "Used when set to 'GD colour' (0-106, like the garage).", "Colors", Int, 12, 0, 106, false, "") \
    X(c_p2_wave_r, "P2 wave trail colour: red", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_wave_g, "P2 wave trail colour: green", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_wave_b, "P2 wave trail colour: blue", "Used by 'Custom RGB' and 'Pulse'.", "Colors", Int, 255, 0, 255, false, "") \
    X(c_p2_copy, "P2 copies P1 colours", "Player 2 uses player 1's colour settings.", "Colors", Toggle, 0, 0, 1, false, "") \
    X(c_rainbow_sat, "Rainbow saturation", "0 = white, 1 = full colour.", "Colors", Float, 0.8, 0, 1, false, "") \
    X(c_rainbow_bright, "Rainbow brightness", "How bright rainbow colours are.", "Colors", Float, 1, 0.1, 1, false, "") \
    X(c_rainbow_spread, "Rainbow offset between parts", "0 = all parts the same colour.", "Colors", Float, 0.5, 0, 1, false, "") \
    X(c_pulse_speed, "Pulse speed", "How fast 'Pulse' colours throb.", "Colors", Float, 1, 0.1, 10, false, "") \
    X(no_trail, "No player trail", "Removes the streak behind your icon.", "Trails", Toggle, 0, 0, 1, false, "") \
    X(no_wave_trail, "No wave trail", "Removes the wave's trail.", "Trails", Toggle, 0, 0, 1, false, "") \
    X(solid_wave, "Solid wave trail", "The wave trail isn't see-through.", "Trails", Toggle, 0, 0, 1, false, "") \
    X(custom_trail, "Custom trail", "Use the trail below (re-open the level to see a change).", "Trails", Toggle, 0, 0, 1, false, "") \
    X(trail_id, "Trail number", "Which trail (1 = default).", "Trails", Int, 1, 1, 15, false, "") \
    X(always_trail, "Always show trail", "Your trail never turns off.", "Trails", Toggle, 0, 0, 1, false, "") \
    X(trail_width, "Trail width", "1 = normal.", "Trails", Float, 1, 0.2, 5, false, "") \
    X(ghost_trail, "Ghost trail", "Afterimages follow your icon, like the ghost trigger.", "Trails", Toggle, 0, 0, 1, false, "") \
    X(wave_width, "Wave trail width", "1 = normal.", "Trails", Float, 1, 0.2, 4, false, "") \
    X(wave_pulse_off, "No wave trail pulse", "The wave trail doesn't pulse to the music.", "Trails", Toggle, 0, 0, 1, false, "") \
    X(rainbow, "Rainbow icons (quick)", "Rainbow main + second colour. Fine-tune in Colors.", "Visual", Toggle, 0, 0, 1, false, "") \
    X(rainbow_speed, "Rainbow speed", "How fast every rainbow effect changes.", "Visual", Float, 1, 0.1, 10, false, "") \
    X(no_transition, "No scene transitions", "Menus switch instantly (no fade).", "Visual", Toggle, 0, 0, 1, false, "") \
    X(unlock_icons, "Unlock all icons", "Use every icon and colour in the garage, even locked ones. Other players can see them on your profile.", "Visual", Toggle, 0, 0, 1, false, "") \
    X(hide_ground, "Hide ground", "No ground or ceiling.", "World", Toggle, 0, 0, 1, false, "") \
    X(hide_background, "Hide background", "Black background.", "World", Toggle, 0, 0, 1, false, "") \
    X(hide_middleground, "Hide middleground", "Hides the middleground layer.", "World", Toggle, 0, 0, 1, false, "") \
    X(hide_player_particles, "Hide player particles", "No dust, ship fire particles, landing puffs...", "World", Toggle, 0, 0, 1, false, "") \
    X(bg_override, "Custom background colour", "Use the RGB below for the background.", "World", Toggle, 0, 0, 1, false, "") \
    X(bg_r, "Background red", "", "World", Int, 40, 0, 255, false, "") \
    X(bg_g, "Background green", "", "World", Int, 40, 0, 255, false, "") \
    X(bg_b, "Background blue", "", "World", Int, 90, 0, 255, false, "") \
    X(ground_override, "Custom ground colour", "Use the RGB below for the ground.", "World", Toggle, 0, 0, 1, false, "") \
    X(ground_r, "Ground red", "", "World", Int, 30, 0, 255, false, "") \
    X(ground_g, "Ground green", "", "World", Int, 30, 0, 255, false, "") \
    X(ground_b, "Ground blue", "", "World", Int, 60, 0, 255, false, "") \
    X(tint_on, "Screen tint", "Puts a coloured layer over the level.", "World", Toggle, 0, 0, 1, false, "") \
    X(tint_r, "Tint red", "", "World", Int, 0, 0, 255, false, "") \
    X(tint_g, "Tint green", "", "World", Int, 0, 0, 255, false, "") \
    X(tint_b, "Tint blue", "", "World", Int, 0, 0, 255, false, "") \
    X(tint_a, "Tint strength", "0 = invisible, 255 = solid.", "World", Int, 80, 0, 255, false, "") \
    X(screen_rotation, "Screen rotation", "Degrees. 180 = upside down.", "World", Float, 0, -180, 180, false, "") \
    X(screen_zoom, "Screen zoom", "1 = normal.", "World", Float, 1, 0.25, 3, false, "") \
    X(screen_flip_x, "Mirror screen", "Flips the whole screen left-right.", "World", Toggle, 0, 0, 1, false, "") \
    X(screen_flip_y, "Flip screen vertically", "Flips the whole screen top-bottom.", "World", Toggle, 0, 0, 1, false, "") \
    X(hud, "Show HUD", "Info text while you play (H toggles it).", "HUD", Toggle, 1, 0, 1, false, "") \
    X(hud_cheat, "Cheat indicator", "Green = legit, red = a cheat is on.", "HUD", Toggle, 1, 0, 1, false, "") \
    X(hud_fps, "FPS", "Frames per second.", "HUD", Toggle, 1, 0, 1, false, "") \
    X(hud_fps_low, "Lowest FPS", "Lowest FPS in the last second (spots lag).", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_frame_ms, "Frame time (ms)", "How long each frame takes.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_cps, "Clicks per second", "Your CPS, best CPS and clicks this attempt.", "HUD", Toggle, 1, 0, 1, false, "") \
    X(hud_best_cps_session, "Best CPS this session", "Your highest CPS since opening the level.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_total_clicks, "Total clicks", "Clicks since opening the level.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_releases, "Releases", "Releases this attempt.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_holding, "Holding", "Shows when you're holding click.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_hold_time, "Hold time", "How long your current / last hold lasted.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_noclip_acc, "Noclip accuracy", "How much of the attempt you were 'alive' with noclip.", "HUD", Toggle, 1, 0, 1, false, "") \
    X(hud_noclip_deaths, "Noclip deaths", "How many times you would have died.", "HUD", Toggle, 1, 0, 1, false, "") \
    X(hud_attempts, "Session attempts", "Attempts since you opened the level.", "HUD", Toggle, 1, 0, 1, false, "") \
    X(hud_attempt_gd, "Attempt number", "The game's own attempt counter.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_session_deaths, "Session deaths", "Deaths since opening the level.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_last_death, "Last death", "Where you died last.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_avg_death, "Average death", "Average % you die at this session.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_session_best, "Session best", "Furthest you got this session.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_best_run, "Best run", "Your best run this session, like 12-54%.", "HUD", Toggle, 1, 0, 1, false, "") \
    X(hud_start_percent, "Attempt started at", "The % this attempt started from.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_percent_left, "Percent left", "How much of the level is left.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_time, "Attempt time", "How long this attempt has lasted.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_session_time, "Time in level", "How long you've played this level since opening it (pauses don't count).", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_level_time, "Level time", "The level's own clock (what time triggers use).", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_tick, "Physics tick", "Which 240 TPS tick you're on.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_jumps, "Jumps", "Jumps this attempt.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_xpos, "X position", "Your horizontal position.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_ypos, "Y position", "Your height.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_yvel, "Y velocity", "How fast you're moving up / down.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_rotation, "Rotation", "Your icon's angle.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_gamemode, "Gamemode", "Cube, ship, ball...", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_portal_speed, "Speed portal", "0.5x, 1x, 2x, 3x, 4x.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_gravity, "Gravity", "Normal or flipped.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_size_mode, "Size", "Mini or normal.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_dual, "Dual", "Shows when you're in dual mode.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_on_ground, "On ground", "Shows when you're on the ground.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_dashing, "Dashing", "Shows during dash orbs.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_direction, "Direction", "Facing left or right (platformer).", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_zoom, "Camera zoom", "The level's camera zoom.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_checkpoints, "Checkpoints", "Practice checkpoints placed.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_level_name, "Level name", "", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_creator, "Creator", "Who made the level.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_level_id, "Level ID", "The ID of the level you're playing.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_stars, "Stars", "The level's star rating.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_object_count, "Object count", "How many objects the level has.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_song_id, "Song ID", "Newgrounds song ID (or built-in song).", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_level_attempts, "Total attempts on level", "All your attempts on this level, ever.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_level_jumps, "Total jumps on level", "All your jumps on this level, ever.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_normal_best, "Your best %", "Your normal mode best.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_practice_best, "Your practice best %", "Your practice mode best.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_startpos, "StartPos number", "Which start position you're on.", "HUD", Toggle, 1, 0, 1, false, "") \
    X(hud_clock, "Clock", "The time on your computer.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_date, "Date", "Today's date.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_mod_count, "Mods loaded", "How many Geode mods you have on.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_window_size, "Window size", "Your game window in pixels.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_custom_text, "Custom text", "Shows your own text (set it in the mod settings).", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_scale, "HUD size", "How big the HUD text is.", "HUD", Float, 1, 0.4, 2.5, false, "") \
    X(hud_opacity, "HUD opacity", "0.1 = almost invisible, 1 = solid.", "HUD", Float, 0.8, 0.1, 1, false, "") \
    X(hud_corner, "HUD corner", "Where the HUD sits.", "HUD", Choice, 0, 0, 3, false, "Top left|Top right|Bottom left|Bottom right") \
    X(hud_font, "HUD font", "", "HUD", Choice, 0, 0, 2, false, "Big|Gold|Chat") \
    X(hud_color_mode, "HUD colour", "Default keeps the coloured lines (cheat indicator etc).", "HUD", Choice, 0, 0, 4, false, "Default|White|Menu colour|Rainbow|Custom RGB") \
    X(hud_r, "HUD red", "Used by 'Custom RGB'.", "HUD", Int, 255, 0, 255, false, "") \
    X(hud_g, "HUD green", "Used by 'Custom RGB'.", "HUD", Int, 255, 0, 255, false, "") \
    X(hud_b, "HUD blue", "Used by 'Custom RGB'.", "HUD", Int, 255, 0, 255, false, "") \
    X(hud_bg, "HUD background", "A dark box behind the HUD so it's easier to read.", "HUD", Toggle, 0, 0, 1, false, "") \
    X(hud_spacing, "HUD line spacing", "1 = normal.", "HUD", Float, 1, 0.5, 2.5, false, "") \
    X(hud_offset_x, "HUD move sideways", "Pixels. Moves the HUD away from its corner.", "HUD", Float, 0, -300, 300, false, "") \
    X(hud_offset_y, "HUD move up / down", "Pixels.", "HUD", Float, 0, -200, 200, false, "") \
    X(no_death_sound, "No death sound", "Mutes the death sound.", "Audio", Toggle, 0, 0, 1, false, "") \
    X(mute_sfx, "Mute sound effects in levels", "Orbs, coins, triggers... all quiet. Music keeps playing.", "Audio", Toggle, 0, 0, 1, false, "") \
    X(pitch_on, "Change pitch", "Plays all sound at the pitch below (on top of speedhack).", "Audio", Toggle, 0, 0, 1, false, "") \
    X(pitch, "Pitch", "1 = normal, 2 = chipmunk, 0.5 = deep.", "Audio", Float, 1, 0.25, 4, false, "") \
    X(click_sound, "Click sound", "Plays a sound every time you click in a level.", "Audio", Toggle, 0, 0, 1, false, "") \
    X(click_volume, "Click sound volume", "", "Audio", Float, 0.5, 0.05, 1, false, "") \
    X(disco, "Disco mode", "The screen flashes through colours.", "Fun", Toggle, 0, 0, 1, false, "") \
    X(disco_speed, "Disco speed", "", "Fun", Float, 1, 0.1, 10, false, "") \
    X(spin_screen, "Spinning screen", "The whole screen slowly spins. Good luck.", "Fun", Toggle, 0, 0, 1, false, "") \
    X(spin_screen_speed, "Screen spin speed", "Turns per minute x 6.", "Fun", Float, 1, 0.1, 10, false, "") \
    X(drunk, "Drunk mode", "The screen sways around.", "Fun", Toggle, 0, 0, 1, false, "") \
    X(earthquake, "Earthquake", "The screen never stops shaking.", "Fun", Toggle, 0, 0, 1, false, "") \
    X(earthquake_strength, "Earthquake strength", "Pixels.", "Fun", Float, 3, 0.5, 20, false, "") \
    X(random_colors, "Random colours every attempt", "New random icon colours each attempt (for parts set to Normal).", "Fun", Toggle, 0, 0, 1, false, "") \
    X(rainbow_bar, "Rainbow progress bar", "", "Fun", Toggle, 0, 0, 1, false, "") \
    X(rainbow_percent, "Rainbow percentage", "", "Fun", Toggle, 0, 0, 1, false, "") \
    X(rainbow_attempt, "Rainbow attempt text", "", "Fun", Toggle, 0, 0, 1, false, "") \
    X(rainbow_bg, "Rainbow background", "", "Fun", Toggle, 0, 0, 1, false, "") \
    X(rainbow_ground, "Rainbow ground", "", "Fun", Toggle, 0, 0, 1, false, "") \
    X(level_page_id, "Level ID on level pages", "Shown in the bottom left of a level's page.", "Extras", Toggle, 1, 0, 1, false, "") \
    X(level_page_objects, "Object count on level pages", "Shows after the level is downloaded.", "Extras", Toggle, 1, 0, 1, false, "") \
    X(level_page_song, "Song ID on level pages", "", "Extras", Toggle, 1, 0, 1, false, "") \
    X(level_cell_id, "Level ID in level lists", "Small ID next to each level's name in search / lists.", "Extras", Toggle, 0, 0, 1, false, "") \
    X(level_cell_objects, "Object count in level lists", "Only for levels you've downloaded.", "Extras", Toggle, 0, 0, 1, false, "") \
    X(text_bypass_chars, "Type any character", "Text boxes accept every character. Servers may still reject odd ones.", "Extras", Toggle, 0, 0, 1, false, "") \
    X(text_bypass_length, "No text length limit", "Text boxes have no character limit. Servers may still cut it off.", "Extras", Toggle, 0, 0, 1, false, "") \
    X(menu_color, "Menu colour", "Accent colour of this menu.", "Menu", Choice, 0, 0, 5, false, "Blue|Purple|Green|Red|Pink|Gold") \
    X(menu_pause, "Pause when opened in a level", "Opening the menu mid-level pauses the game.", "Menu", Toggle, 1, 0, 1, false, "") \
    X(menu_remember_tab, "Remember last tab", "Re-opens on the tab you used last.", "Menu", Toggle, 1, 0, 1, false, "") \
    X(menu_scale, "Menu size", "Close and re-open the menu to apply.", "Menu", Float, 1, 0.6, 1.3, false, "") \
    X(menu_dim, "Menu background darkness", "0 = see-through, 255 = black. Re-open to apply.", "Menu", Int, 150, 0, 255, false, "") \
    X(key_notifications, "Key popups", "Show a little popup when you press a hack key.", "Menu", Toggle, 1, 0, 1, false, "") \
    X(main_menu_button, "OV button on main menu", "Takes effect next time the main menu opens.", "Menu", Toggle, 1, 0, 1, false, "") \
    X(pause_button, "OV button in pause menu", "", "Menu", Toggle, 1, 0, 1, false, "")

enum class H : int {
#define OV_ENUM(id, ...) id,
    OV_HACKS(OV_ENUM)
#undef OV_ENUM
    COUNT
};

struct HackDef {
    H h;
    char const* key;
    char const* name;
    char const* desc;
    char const* category;
    Type type;
    double def, min, max;
    bool cheat;
    char const* choices;  // "A|B|C"
};

std::vector<HackDef> const& defs();
std::vector<std::string> const& categories();
std::vector<std::string> choicesOf(HackDef const& d);
HackDef const& def(H h);

double get(H h);
inline bool on(H h) { return get(h) != 0; }
inline int geti(H h) { return static_cast<int>(get(h)); }
inline float getf(H h) { return static_cast<float>(get(h)); }
void set(H h, double v);   // clamps, saves
void loadAll();
void resetAll();
unsigned changeCounter();  // goes up every time any option changes

// live state set by keys
extern bool g_slowmoHeld;

// what's actually in effect right now (depends on practice mode etc.)
bool noclipActive();
float levelSpeed();        // game speed inside a level
float effectiveSpeed();    // game speed right now (menus included)

// true if a cheat is in effect right now
bool cheating();
std::string cheatList();   // names of the cheats in effect

} // namespace ov
